### PR TITLE
Update to latest release.

### PR DESCRIPTION
**Pull request by vamega**

### CODE REVIEW

**Comment by frol** [comment]
@vamega Please, update MD5 checksum as well.

**Comment by vamega** [comment]
Done. Sorry about that.

**Comment by frol** [comment]
@jakirkham Is it a known issue of Travis builds failure?

**Comment by jakirkham** [comment]
It seems to be occurring a bit with Travis CI in last hour at least. Not sure why it is occurring.

**Comment by frol** [comment]
@jakirkham Should we wait for new conda release or will you guys push global update with swapping conda-channels-add with conda-show-urls?

**Comment by ocefpaf** [comment]
@frol I re-stared the CIs here. I believe that the issue is resolved.

**Pull request merged**
